title: Nayla Hana # your name (or website title) here
logo: "/images/fotoaku.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br> Hello, everyone!<br>
  Second description 
  <br>Please call me, Nayla!<br>
  <a href="https://www.linkedin.com/in/naylahana/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
